[package]
name = "w2w"
version = "0.1.4"
authors = ["gkourgkoutas"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.26"
wikipedia = "0.5.0"
regex = "1.11.1"