[package]
name = "w2w"
version = "0.1.2"
authors = ["gkourgkoutas"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.21"
wikipedia = "0.3.4"
regex = "1.5"