[package]
name = "w2w"
version = "0.1.3"
authors = ["gkourgkoutas"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.26"
wikipedia = "0.3.4"
regex = "1.6"