[package]
name = "w2w"
version = "0.1.0"
authors = ["gkourgkoutas"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.17"
wikipedia = "0.3.4"
# array_tool = "1.0.3"